templates:
    -
        path:    "NSCmsBundle:Pages:page.html.twig"
        title:   "Default page template"
        default: true
        areas:
            -
                name: menu
                title: "Меню"
                fixed: true
            -
                name: left
                title: "Левая панель"
                fixed: true
            -
                name: content
                title: "Контентная область"
            -
                name: footer
                title: "Нижняя область"
                fixed: true
