parameters:
#    im_front.example.class: IM\FrontBundle\Example

services:
#    im_front.example:
#        class: %im_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
